modified pipeline [WIP]

diff --git a/.github/workflows/java-app-deployment.yaml b/.github/workflows/java-app-deployment.yaml
--- a/.github/workflows/java-app-deployment.yaml
+++ b/.github/workflows/java-app-deployment.yaml
@@ -33,7 +33,19 @@ jobs:
             exit 1
           fi
 
-      # Step 4: Download Datadog Java Agent
+      # Step 4: Manually Run Spring Boot Repackage
+      - name: Manually Run Spring Boot Repackage
+        working-directory: ./Application
+        run: |
+          mvn spring-boot:repackage -e -X
+          if [ -f "target/hello-world-app-1.0-SNAPSHOT.jar" ]; then
+            echo "Fat JAR built successfully."
+          else
+            echo "ERROR: Fat JAR file not found in target directory!" >&2
+            exit 1
+          fi
+
+      # Step 5: Download Datadog Java Agent
       - name: Download Datadog Java Agent
         working-directory: ./Application
         run: curl -Lo dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'
@@ -59,7 +71,7 @@ jobs:
         working-directory: ./Application
         run: chmod 644 Dockerfile app.jar dd-java-agent.jar
 
-      # Step 5: Log in to GitHub Container Registry
+      # Step 6: Log in to GitHub Container Registry
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
         with:
@@ -67,13 +79,13 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      # Step 6: Build Docker Image
+      # Step 7: Build Docker Image
       - name: Build Docker Image
         working-directory: ./Application
         run: |
           docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/hello-world-app:${{ github.run_number }} -f Dockerfile .
 
-      # Step 7: Push Docker Image to GitHub Packages
+      # Step 8: Push Docker Image to GitHub Packages
       - name: Push Docker Image
         run: |
           docker push ghcr.io/${{ github.repository_owner }}/hello-world-app:${{ github.run_number }}
